random_seed: 7
graph:
  source: "osmnx" # "gis-f2e"
  name: "hartford" # "Santa Ana, CA" # "surat"
  diameter: 8.0 # 8.0 # 11.5
  max_weight: 1597.949 # 1438.266
  file_path: "../data/{name}.{source}"
  download_type: "drive"
  coord_path: "../data/{name}.co"
  plot_path: "../plots/{name}"
aneda:
  "device": "cuda:2"
  "embedding_dim": 128
  "batch_size": 0
  "epochs": 1000 # 1000
  "lr": 0.01 # 0.0003
  "loss_func": "mre" # "mre", "mse", "poisson"
  "optimizer": "adam" # "adam", "sgd"
  "sample_ratio": 0.03
  "test_sample_ratio": 0.05

  "init_embedding": "node2vec" # "coord" "node2vec" "grarep" "none"
  "measure": "norm" # "norm" "spherical" "hyperbolic" "lat-long" "inv-dot"
  "norm": 2

run_routing: False
run_dist_routing: False
run_time_test: False
run_dist_time_test: False
plot_routes: False
test_results: False
demo: True

grarep:
  "embedding_dim": 128
  "iterations": 10
  "order": 100
node2vec:
  "embedding_dim": 128
  "walk_length": 80
  "window_size": 10
  "p": 1
  "q": 1
  "num_walks": 10
  "epochs": 100
  "batch_size": 256
  "lr": 0.01


plot:
  plot_nx_graph: False
val_size: 0.2 # val/train = 20% / 80%, for training
log_path: "../output/logs"
force_recreate_train_and_val_sets: False
force_recreate_test_set: False
write_train_val_sets: True
write_test_set: True
parse_tuning_param_by: ->  ## helpful to create a list of configs
routing_num_samples: 25000
# df = pd.read_csv("routes.csv", names=["source", "target", "numVisited", "pathLength"])